# **This notebook showcases the construction of the additional features (technical indicators) and the feature selection methods that has been implemented**

# **Installing packages**

In [1]:
!pip install ta

Collecting ta
  Downloading ta-0.9.0.tar.gz (25 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from ta) (1.19.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from ta) (1.1.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->ta) (1.15.0)
Building wheels for collected packages: ta
  Building wheel for ta (setup.py) ... done
  Created wheel for ta: filename=ta-0.9.0-py3-none-any.whl size=28908 sha256=86a571a6f68b33b622a45256a7c8321d5c398bf84885e401fcdef259e09933fb
  Stored in directory: /root/.cache/pip/wheels/72/78/64/cc1c01506a1010a9845e9bd7c69333730f7174661228ea4f98
Successfully built ta
Installing collected packages: ta
Successfully installed ta-0.9.0

# **Importing packages**

In [2]:
import pandas as pd 
import numpy as np

from ta import momentum, trend, volatility, volume, others
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

# **Loading data**

In [4]:
df = pd.read_csv('apple.csv', header=0, parse_dates=[0], index_col=0, squeeze=True)
df

                  open        high         low  ...      CCI_14    ROC_10     RSI_14
date                                            ...
2015-01-02   27.847500   27.860001   26.837500  ...         NaN       NaN        NaN
2015-01-05   27.072500   27.162500   26.352501  ...         NaN       NaN        NaN
2015-01-06   26.635000   26.857500   26.157499  ...         NaN       NaN        NaN
2015-01-07   26.799999   27.049999   26.674999  ...         NaN       NaN        NaN
2015-01-08   27.307501   28.037500   27.174999  ...         NaN       NaN        NaN
...                ...         ...         ...  ...         ...       ...        ...
2021-03-25  119.540001  121.660004  119.000000  ...  -54.510961 -1.123322  43.713712
2021-03-26  120.349998  121.480003  118.919998  ...  -64.627979  0.148723  44.995052
2021-03-29  121.650002  122.580002  120.730003  ...  -17.921375 -2.096943  45.383781
2021-03-30  120.110001  120.400002  118.860001  ... -105.699850 -4.515408  42.694043
2021-03-31  121.650002  123.519997  121.150002  ...   19.939937 -2.092017  47.731710

[1572 rows x 42 columns]

# **Drop old features**

In [5]:
df.columns

Index(['open', 'high', 'low', 'close', 'adj_close', 'volume', 'current_ratio',
       'long-term_debt_to_capital', 'debt_to_equity_ratio', 'gross_margin',
       'operating_margin', 'ebit_margin', 'ebitda_margin',
       'pre-tax_profit_margin', 'net_profit_margin', 'asset_turnover',
       'inventory_turnover_ratio', 'receiveable_turnover',
       'days_sales_in_receivables', 'roe_-_return_on_equity',
       'return_on_tangible_equity', 'roa_-_return_on_assets',
       'roi_-_return_on_investment', 'book_value_per_share',
       'operating_cash_flow_per_share', 'free_cash_flow_per_share',
       'is_day_start_market', 'is_day_end_market', 'day_of_week', 'SMA_5',
       'SMA_10', 'SMA_20', 'SMA_50', 'EMA_5', 'EMA_10', 'EMA_20', 'EMA_50',
       'ATR_14', 'ADX_14', 'CCI_14', 'ROC_10', 'RSI_14'],
      dtype='object')

In [6]:
# We keep only the OHLCV data 
df = df[['open', 'high', 'low', 'close', 'adj_close', 'volume']]

# **Computing technical indicators**

We are creating features as technical indicators that are set for different time-ranges from 5 to 50 days, with 5 days of difference. They are the following:

- SMA: Simple Moving Average.
- EMA: Exponential Moving Average.
- ATR: Average True Range.
- ADX: Average Directional Index.
- CCI: Commodity Channel Index.
- ROC: Rate of Change.
- RSI: Relative Strength Index.
- Force Index.
- MFI: Money Flow Index.
- OBV: On Balance Volume.
- UI: ULCER Index.

In [ ]:
f_names = []
for i in range(5, 51, 5):
    # SMA
    n = trend.sma_indicator.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = trend.sma_indicator(df.close, i, fillna=False)
    # EMA
    n = trend.ema_indicator.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = trend.ema_indicator(df.close, i, fillna=False)
    # ATR
    n = volatility.average_true_range.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = volatility.average_true_range(df.high, df.low, df.close, i, fillna=False)
    # ADX
    n = trend.adx.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = trend.adx(df.high, df.low, df.close, i, fillna=False)
    # CCI
    n = trend.cci.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = trend.cci(df.high, df.low, df.close, i, fillna=False)
    # ROC
    n = momentum.roc.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = momentum.roc(df.close, i, fillna=False)
    # RSI
    n = momentum.rsi.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = momentum.rsi(df.close, i, fillna=False)
    # Force index
    n = volume.force_index.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = volume.force_index(df.close, df.volume, i, fillna=False)
    # MFI
    n = volume.money_flow_index.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = volume.money_flow_index(df.high, df.low, df.close, df.volume, i, fillna=False)
    # OBV
    n = volume.on_balance_volume.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] = volume.on_balance_volume(df.close, df.volume, i)
    # UI
    n =  volatility.ulcer_index.__name__ + str(i)
    print(n)
    f_names.append(n)
    df[n] =  volatility.ulcer_index(df.close, i, fillna=False)

# Add features to the dataset
f_names.extend([volume.acc_dist_index.__name__, others.cumulative_return.__name__, others.daily_log_return.__name__, others.daily_return.__name__])

df[volume.acc_dist_index.__name__] = volume.acc_dist_index(df.high, df.low, df.close, df.volume, fillna=False)

df[others.cumulative_return.__name__] =  others.cumulative_return(df.close, fillna=False)
  
df[others.daily_log_return.__name__] =  others.daily_log_return(df.close, fillna=False)
  
df[others.daily_return.__name__] =  others.daily_return(df.close, fillna=False)

sma_indicator5
ema_indicator5
average_true_range5
adx5
cci5
roc5
rsi5
force_index5
money_flow_index5
on_balance_volume5
ulcer_index5
sma_indicator10
ema_indicator10
average_true_range10
adx10

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

cci10
roc10
rsi10
force_index10
money_flow_index10
on_balance_volume10
ulcer_index10
sma_indicator15
ema_indicator15
average_true_range15
adx15
cci15

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

roc15
rsi15
force_index15
money_flow_index15
on_balance_volume15
ulcer_index15
sma_indicator20
ema_indicator20
average_true_range20
adx20
cci20
roc20
rsi20
force_index20
money_flow_index20
on_balance_volume20
ulcer_index20
sma_indicator25
ema_indicator25
average_true_range25
adx25
cci25
roc25
rsi25
force_index25
money_flow_index25
on_balance_volume25
ulcer_index25
sma_indicator30
ema_indicator30
average_true_range30

/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

adx30
cci30
roc30
rsi30
force_index30
money_flow_index30
on_balance_volume30
ulcer_index30
sma_indicator35
ema_indicator35
average_true_range35
adx35

/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

cci35
roc35
rsi35
force_index35
money_flow_index35
on_balance_volume35
ulcer_index35
sma_indicator40
ema_indicator40
average_true_range40
adx40
cci40
roc40
rsi40
force_index40
money_flow_index40
on_balance_volume40
ulcer_index40
sma_indicator45
ema_indicator45
average_true_range45
adx45
cci45
roc45
rsi45
force_index45
money_flow_index45
on_balance_volume45
ulcer_index45

/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/usr/local/lib/python3.7/dist-packages/ta/trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

sma_indicator50
ema_indicator50
average_true_range50
adx50
cci50
roc50
rsi50
force_index50
money_flow_index50
on_balance_volume50
ulcer_index50

In [ ]:
# Check the new dataset's columns
df.columns

Index(['open', 'high', 'low', 'close', 'adj_close', 'volume', 'sma_indicator5',
       'ema_indicator5', 'average_true_range5', 'adx5',
       ...
       'roc50', 'rsi50', 'force_index50', 'money_flow_index50',
       'on_balance_volume50', 'ulcer_index50', 'acc_dist_index',
       'cumulative_return', 'daily_log_return', 'daily_return'],
      dtype='object', length=120)

# **Data preparation**

## **Data shifting**

**A necessary step when dealing with Time series is to make the dataset suitable to supervised learning models, or simply "data shifting".**

In [ ]:
# Shift the close price upwards
df['close'] = df['close'].shift(-1)
df

                  open        high  ...  daily_log_return  daily_return
date                                ...
2015-01-02   27.847500   27.860001  ...               NaN    -46.648777
2015-01-05   27.072500   27.162500  ...         -2.857602     -2.817159
2015-01-06   26.635000   26.857500  ...          0.009415      0.009416
2015-01-07   26.799999   27.049999  ...          1.392477      1.402217
2015-01-08   27.307501   28.037500  ...          3.770252      3.842227
...                ...         ...  ...               ...           ...
2021-03-25  119.540001  121.660004  ...          0.415490      0.416354
2021-03-26  120.349998  121.480003  ...          0.512824      0.514141
2021-03-29  121.650002  122.580002  ...          0.148392      0.148503
2021-03-30  120.110001  120.400002  ...         -1.235042     -1.227446
2021-03-31  121.650002  123.519997  ...          1.859174      1.876564

[1572 rows x 120 columns]

## **Dropping rows with Nan values**

**While the Nan values are available only on the first 50 days, which caused by the computation of technical indicators for the 50 day range, the close price isn't affected by these days, especially with the lack of fluctuations and volatility during the first 50 days in the dataset. Therefore, dropping these values won't cause any harm.**

In [ ]:
# Drop the Nan values
df = df.dropna()
df

                  open        high  ...  daily_log_return  daily_return
date                                ...
2015-03-17   31.475000   31.830000  ...          1.658837      1.672672
2015-03-18   31.750000   32.290001  ...          1.119342      1.125630
2015-03-19   32.187500   32.312500  ...         -0.757905     -0.755040
2015-03-20   32.062500   32.099998  ...         -1.262842     -1.254902
2015-03-23   31.780001   31.962500  ...          1.035132      1.040508
...                ...         ...  ...               ...           ...
2021-03-24  122.820000  122.900002  ...         -2.019609     -1.999351
2021-03-25  119.540001  121.660004  ...          0.415490      0.416354
2021-03-26  120.349998  121.480003  ...          0.512824      0.514141
2021-03-29  121.650002  122.580002  ...          0.148392      0.148503
2021-03-30  120.110001  120.400002  ...         -1.235042     -1.227446

[1521 rows x 120 columns]

# **Feature selection**

**In this section, we will introduce the three methods for feature selection.**

## **Filter methods**

### **Most Correlated features with the target**

In [ ]:
# Create the correlation matrix
corr = df.corr()[['close']]

# Chosing the features that are correlated (above 0.9),
# or negatively correlated with the target (below -0.9)
F1 = corr[abs(corr['close']) > 0.9].index.tolist()
F1

['open',
 'high',
 'low',
 'close',
 'adj_close',
 'sma_indicator5',
 'ema_indicator5',
 'sma_indicator10',
 'ema_indicator10',
 'sma_indicator15',
 'ema_indicator15',
 'sma_indicator20',
 'ema_indicator20',
 'sma_indicator25',
 'ema_indicator25',
 'average_true_range25',
 'sma_indicator30',
 'ema_indicator30',
 'average_true_range30',
 'sma_indicator35',
 'ema_indicator35',
 'average_true_range35',
 'sma_indicator40',
 'ema_indicator40',
 'average_true_range40',
 'sma_indicator45',
 'ema_indicator45',
 'average_true_range45',
 'sma_indicator50',
 'ema_indicator50',
 'average_true_range50',
 'cumulative_return']

### **F-regression test**

In [ ]:
from sklearn.datasets import make_regression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

data = df.drop('close', axis = 1)
fs = SelectKBest(score_func = f_regression, k = 15)
fs_tr = fs.fit_transform(data, df.close)
F2 = data.columns[(fs.get_support())].tolist()
F2

['open',
 'high',
 'low',
 'adj_close',
 'sma_indicator5',
 'ema_indicator5',
 'sma_indicator10',
 'ema_indicator10',
 'sma_indicator15',
 'ema_indicator15',
 'sma_indicator20',
 'ema_indicator20',
 'ema_indicator25',
 'ema_indicator30',
 'cumulative_return']

## **Embedded methods**

### **RandomForestRegressor**

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel

data = df.drop('close', axis = 1)
sel = SelectFromModel(RandomForestRegressor(n_estimators = 500))
sel.fit(data, df.close.values)
F3 = data.columns[(sel.get_support())].tolist()
F3

['open',
 'high',
 'low',
 'adj_close',
 'ema_indicator5',
 'acc_dist_index',
 'cumulative_return']

### **Lasso regularization**

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Lasso

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df, df.close, test_size=0.2, shuffle=False)

In [ ]:
pipeline = Pipeline([
                     ('scaler', MinMaxScaler()),
                     ('model', Lasso())
])

In [ ]:
search = GridSearchCV(pipeline,
                      {'model__alpha':np.arange(0.1,10,0.1)}, 
                      scoring="neg_mean_squared_error",
                      cv=None
                      )

search.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.198e+01, tolerance: 1.591e+01
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.366e+01, tolerance: 1.352e+01
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.317e+01, tolerance: 1.274e+01
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.810e+01, tolerance: 1.352e+01
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive

GridSearchCV(estimator=Pipeline(steps=[('scaler', MinMaxScaler()),
                                       ('model', Lasso())]),
             param_grid={'model__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9,
       4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2,
       5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5,
       6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8,
       7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1,
       9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])},
             scoring='neg_mean_squared_error')

**The importance of a feature is the absolute value of its coefficient.**

In [ ]:
coefficients = search.best_estimator_.named_steps['model'].coef_
importance = np.abs(coefficients)

In [ ]:
F4 = np.array(df.columns)[importance > 0].tolist()
F4

['close',
 'ema_indicator10',
 'ema_indicator15',
 'ema_indicator20',
 'ema_indicator50',
 'acc_dist_index']

## **Wrapper methods**

### **Bi-directional elimination (Step-wise Selection)**

In [ ]:
scaler = MinMaxScaler()
df_scaled =  df.copy()

df_scaled[df.columns.tolist()] = scaler.fit_transform(df_scaled[df.columns.tolist()])

In [ ]:
def stepwise_selection(data, target,SL_in=0.05,SL_out = 0.05):
    initial_features = data.columns.tolist()
    best_features = []

    while (len(initial_features) > 0):
        remaining_features = list(set(initial_features)-set(best_features))
        new_pval = pd.Series(index = remaining_features)
        for new_column in remaining_features:
            model = sm.OLS(target, sm.add_constant(data[best_features+[new_column]])).fit()
            new_pval[new_column] = model.pvalues[new_column]
        min_p_value = new_pval.min()
        if (min_p_value < SL_in):
            best_features.append(new_pval.idxmin())
            while (len(best_features) > 0):
                best_features_with_constant = sm.add_constant(data[best_features])
                p_values = sm.OLS(target, best_features_with_constant).fit().pvalues[1:]
                max_p_value = p_values.max()
                if (max_p_value >= SL_out):
                    excluded_feature = p_values.idxmax()
                    best_features.remove(excluded_feature)
                else:
                    break 
        else:
            break
    return best_features

In [ ]:
data = df_scaled.drop('close', axis = 1)

In [ ]:
F5 = stepwise_selection(data, df_scaled.close)
F5

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  import sys

['low', 'cumulative_return', 'open', 'high', 'daily_return']

## **Set of all features**

In [ ]:
all_F = F1 + F2 + F3 + F4 + F5

In [ ]:
all_F = list(set(all_F))
all_F

['ema_indicator40',
 'adj_close',
 'daily_return',
 'cumulative_return',
 'sma_indicator25',
 'ema_indicator20',
 'sma_indicator5',
 'ema_indicator10',
 'ema_indicator45',
 'average_true_range45',
 'low',
 'close',
 'ema_indicator15',
 'ema_indicator5',
 'average_true_range30',
 'open',
 'average_true_range50',
 'acc_dist_index',
 'sma_indicator20',
 'sma_indicator10',
 'average_true_range25',
 'ema_indicator50',
 'sma_indicator45',
 'sma_indicator35',
 'sma_indicator15',
 'ema_indicator25',
 'sma_indicator50',
 'sma_indicator40',
 'ema_indicator35',
 'ema_indicator30',
 'average_true_range40',
 'high',
 'sma_indicator30',
 'average_true_range35']

In [ ]:
# Saving the new dataset
df = df[all_F]
df.to_csv('new_apple_f.csv')